server {
    listen 80;
    server_name localhost;

    # Tarayıcıdan gelen normal isteklerde HTML/JS/CSS dosyalarını ver
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ =404;
    }

    # /api/ ile başlayan istekleri arka plandaki Go servisine ilet (Reverse Proxy)
    location /api/ {
        # Sonda bulunan '/' çok önemlidir. /api/start isteğini go-api:8080/start olarak çevirir.
        proxy_pass http://go-api:8080/;
        
        # Tarayıcı her şeyi aynı origin'den (localhost:3000) geldiği için
        # karmaşık CORS (Access-Control) header'larına artık ihtiyacın yok!
    }
}