# 1. SUNUCU: Sadece Arayüzü (HTML) Verir
server {
    listen 80;
    server_name index.test; # Arayüze bu isimle gireceksin

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }
}

# 2. SUNUCU: Sadece Go API İsteklerini Karşılar
server {
    listen 80;
    server_name go.api; # API istekleri bu isme gelecek

    location / {
        # Tarayıcının güvenlik (Preflight / OPTIONS) sorgusuna izin ver

        if ($request_method = 'OPTIONS') {
            add_header 'Access-Control-Allow-Origin' 'http://index.test:3000';
            add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
            add_header 'Access-Control-Allow-Headers' '*';
            add_header 'Content-Type' 'text/plain; charset=utf-8';
            add_header 'Content-Length' 0;
            return 204; # <--- Bu satır olmadan tarayıcı ikna olmaz!
        }
        # Gerçek isteklere de CORS izni ver
        add_header 'Access-Control-Allow-Origin' 'http://index.test:3000' always;
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS' always;

        # Go API'ye yönlendir
        proxy_pass http://go-api:8080/;
    }
}