FROM golang:1.25-alpine AS build

WORKDIR /src

RUN apk add --no-cache ca-certificates

COPY go.mod go.sum ./
RUN go mod download

COPY . ./
#Burada src 
#tüm dosyaları kopyalama sebebi
RUN CGO_ENABLED=0 GOOS=linux go build -o /out/go-api . 
#farlklı os ler için aynı anda nasıl derlenebilir

FROM alpine:3.20 
#alpine dışında ne kullanılabilir(scratch,debian)

RUN apk add --no-cache ca-certificates \
	&& addgroup -S app \
	&& adduser -S app -G app

WORKDIR /app

COPY --from=build /out/go-api /app/go-api

USER app

ENTRYPOINT ["/app/go-api"] 
#entrypoing cmd farkı