services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: natslog-jenkins
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      # Jenkins'in host'taki Docker daemon'ı kullanabilmesi için socket mount
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - natslog-net

  go-api:
    build:
      context: ./go-api
      dockerfile: Dockerfile
    container_name: nats-log-go-api
    restart: unless-stopped
    env_file:
      - ./go-api/.env
    ports:
      - "8081:8081"
    networks:
      - natslog-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nats-log-frontend
    restart: unless-stopped
    depends_on:
      - go-api
    ports:
      - "3000:3000"
    networks:
      - natslog-net

volumes:
  jenkins_home:

networks:
  natslog-net:
    driver: bridge