pipeline{
    agent any

    

    stages{
            stage('Checkout'){
                steps{
                    checkout scm
                }
            }

            stage('Go Vet'){
                steps{
                    dir('docs/intern/NATS-LOG/go-api'){
                        sh 'go vet ./...'
                    }
                }
            }

            stage('Docker Build'){
                steps{
                    sh 'docker compose build'
                }
            }

            stage('Deploy'){
            
                steps{
                    sh 'docker compose up'
                }
            }
        }
    }
