pipeline{
    agent any

    stages{
            stage('Checkout'){
                steps{
                    checkout scm
                }
            }

            stage('Go Vet'){
                steps{
                    dir('docs/intern/NATS-LOG/go-api'){
                        sh 'go vet ./...'
                    }
                }
            }

            stage('Install Docker Compose') {
                steps {
                    dir('docs/intern/NATS-LOG') {
                        // Docker Compose aracını o anki workspace içine indiriyoruz
                        sh 'curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o docker-compose'
                        // İndirdiğimiz dosyaya çalıştırma yetkisi veriyoruz
                        sh 'chmod +x docker compose'
                    }
                }
            }

            stage('Docker Build'){
                steps{
                    sh 'docker compose build'
                }
            }

            stage('Deploy'){

                steps{
                    sh 'docker compose up'
                }
            }
        }
    }
