name: nats-log

services:
  nats:
    image: nats:2.10.2
    container_name: nats-log
    restart: unless-stopped
    command: ["-c", "/etc/nats/nats.conf"]
    ports:
      - "${NATS_CLIENT_PORT:-4222}:4222"  
      - "${NATS_MONITOR_PORT:-8222}:8222"
      - "${NATS_WEBSOCKET_PORT:-8880}:8888"
      #Portlarda hangisi container'a giriş için hangisi host'a giriş ve env ile bu şekilde kullanılmasının sebebi nedir?
    environment:
      NATS_USER: usr
      NATS_PASSWORD: usr1935
    volumes:
      - ./nats/nats.conf:/etc/nats/nats.conf:ro
      - nats-data:/data
    networks:
      - nats-log-network

  go-api:
    build:
      context: ./go-api
      dockerfile: ./DockerFile
    container_name: nats-log-go-api
    restart: unless-stopped
    ports:
      - "${GO_API_PORT:-9222}:9222"
    depends_on:
      - nats
    environment:
      NATS_URL: nats://usr:usr1935@nats:4222
      NATS_SUBJECT_PREFIX: logs.size
      POLL_INTERVAL: 1s
      LOG_PATHS: /app/logs
      APP_LOG_LEVEL: info
    volumes:
      - /var/log:/app/logs:ro
    networks:
      - nats-log-network

  frontend:
    build:
      context: ./frontend
      dockerfile: ./DockerFile
    container_name: nats-log-frontend
    restart: unless-stopped
    ports:
      - "${FRONTEND_PORT:-8080}:8080"
    depends_on:
      - go-api
    environment:
      GO_API_URL: http://go-api:9222
    networks:
      - nats-log-network

  frontend:
    build:
      context: ./frontend
      dockerfile: ./DockerFile
    container_name: nats-log-frontend
    restart: unless-stopped
    ports:
      - "3000:80" # Tarayıcıya http://localhost:3000 olarak açılacak
    depends_on:
      - nats
      - go-api
    networks:
      - nats-log-network

networks:
  nats-log-network:
    driver: bridge

volumes:
  nats-data: