port: 4222
http: 8222

authorization {
  users = [
    {
      user: "${NATS_USER}"
      password: "${NATS_PASSWORD}"
      permissions: {
        publish: ["logs.size.>"]
        subscribe: ["logs.size.>"]
      }
    }
  ]
}
