port: 4222
http: 8222

websocket {
  port: 8888
  no_tls: true
}

authorization {
  users = [
    {
      user: "usr"
      password: "usr1935"
      permissions: {
        publish: ["logs.size.>"]
        subscribe: ["logs.size.>"]
      }
    }
  ]
}